#!/bin/ksh -p

# For more detailed documentation, see zrep.txt or zrep.overview.txt
ZREP_VERSION=1.0.1

######## start of included files from zrep_top here
AWKinclude zrep_vars
AWKinclude zrep_status
AWKinclude zrep_snap
AWKinclude zrep_sync
AWKinclude zrep_failover

######## zrep_top continues here

usage(){
	echo zrep v${ZREP_VERSION}: a program to replicate a zfs filesystem to another
	echo in an ongoing basis.
	echo More documentation at a later date.
	echo "  Philip Brown, 2012"
	echo ""
	echo Simple usage summary:
	echo 'zrep (init|-i) ZFS/fs remotehost remoteZFSpool/fs'
	echo 'zrep (sync|-S) [-q seconds] ZFS/fs'
	echo 'zrep (sync|-S) [-q seconds] all'
	echo 'zrep (sync|-S) ZFS/fs@snapshot    -- temporary retroactive sync'
	echo 'zrep (status|-s) [-v] [(-a|ZFS/fs)]'
	echo 'zrep refresh ZFS/fs               -- pull version of sync'
	echo 'zrep (list|-l) [-v]'
	echo 'zrep (expire|-e) [-L] (ZFS/fs ...)|(all)|()'
	echo 'zrep (changeconfig|-C) ZFS/fs remotehost remoteZFSpool/fs'
	echo 'zrep failover [-L] ZFS/fs'
	echo 'zrep takeover [-L] ZFS/fs'
	echo 'zrep clear ZFS/fs  -- REMOVE ZREP CONFIG AND SNAPS FROM FILESYSTEM'
	echo
	echo '   -q option says to Quietly ignore locked filesystems that have synced'
	echo '      more recently than the given amount of seconds'
	echo
	echo 'Paired commands for high-transaction systems:'
	echo '   zrep snaponly ZFS/fs'
	echo '   zrep synconly ZFS/fs'
	echo 'The above two commands split the simple sync subcommand, into two'
	echo 'separate steps, so that a database, etc. may resume while the sync'
	echo 'completes in the background'
	echo ''
	echo ' More detailed examples can be found at:'
	echo http://www.bolthole.com/solaris/zrep/zrep.documentation.html
}

case "$1" in
	"")
		usage
		;;
	clear)
		shift
		zrep_clear $1
		;;
	expire|-e)
		shift
		zrep_expire "$@"
		;;
	init|-i)
		shift
		zrep_init "$@"
		;;
	changeconfig|-C)
		shift
		zrep_changeconfig "$@"
		;;
	sync|-S)
		shift
		zrep_sync "$@"
		;;
	snaponly)
		shift
		zrep_snaponly "$@"
		;;
	synconly)
		shift
		zrep_synconly "$@"
		;;
	refresh)	# yes keep this in this order
		shift
		zrep_refresh "$@"
		;;
	status|-s)
		shift
		zrep_status "$@"
		;;
	list|-l)
		shift
		zrep_list "$@"
		;;
	failover)
		shift
		zrep_failover "$@"
		;;
	takeover)
		shift
		zrep_takeover "$@"
		;;
		
	_refreshpull)  # Secret option DO NOT PUT IN USAGE!!
		shift
		_refreshpull $1
		;;
	*)
		usage
		;;
esac


